import { useEffect, useMemo, useState } from "react";
import TagPill from "../components/TagPill";
import PoiCard from "../components/PoiCard";
import SiteDetailModal from "../components/SiteDetailModal";
import { useCity } from "../lib/CityContext";
import { useTranslation } from "../lib/LanguageContext";
import { useWikiThumbnail } from "../lib/useWikiThumbnail";
import { haversineMeters, getCurrentPosition } from "../lib/geo";
import { CATEGORIES as SITE_CATEGORIES, CATEGORY_ACCENTS, CATEGORY_LABEL_KEYS, normalizeCategory } from "../lib/categories";
import { track } from "../lib/analytics";
import { useTrackScreen } from "../lib/useTrackScreen";
import type { Site } from "../lib/types";

const CATEGORIES = [
  "All",
  ...SITE_CATEGORIES,
];

function formatDistance(meters: number | null): string {
  if (meters === null) return "";
  if (meters < 1000) return `${Math.round(meters)} M`;
  return `${(meters / 1000).toFixed(1)} KM`;
}

function PoiCardWithImage({
  site,
  distance,
  onClick,
}: {
  site: Site;
  distance: string;
  onClick: () => void;
}) {
  const { t, language } = useTranslation();
  const imageUrl = useWikiThumbnail(site.name);
  const name = language === "ar" && site.name_ar ? site.name_ar : site.name;
  const description = language === "ar" && site.description_ar ? site.description_ar : site.description;
  return (
    <PoiCard
      name={name}
      distance={distance}
      category={t(CATEGORY_LABEL_KEYS[normalizeCategory(site.category)]).toUpperCase()}
      description={description}
      imageUrl={site.image_url || imageUrl}
      categoryAccent={CATEGORY_ACCENTS[normalizeCategory(site.category)]}
      onClick={onClick}
    />
  );
}

export default function Explore() {
  const { city, sites, heroImageUrl, status, error, locate } = useCity();
  const { t } = useTranslation();
  const [activeCategory, setActiveCategory] = useState("All");
  const [userPos, setUserPos] = useState<{ lat: number; lng: number } | null>(null);
  const [heroImageFailed, setHeroImageFailed] = useState(false);
  const [heroFallbackFailed, setHeroFallbackFailed] = useState(false);
  const [selectedSiteName, setSelectedSiteName] = useState<string | null>(null);

  // heroImageUrl comes from a cached DB value (CityContext's getCityHero) that can go stale --
  // e.g. a thumbnail URL generated by older code that Wikimedia's resizer now rejects. If it
  // fails to load, fall back to a fresh title lookup instead of giving up to a flat gradient.
  const freshHeroImageUrl = useWikiThumbnail(city?.name);
  const heroImagePrimaryOk = Boolean(heroImageUrl) && !heroImageFailed;
  const heroImageFallbackOk =
    !heroImagePrimaryOk && Boolean(freshHeroImageUrl) && freshHeroImageUrl !== heroImageUrl && !heroFallbackFailed;
  const displayedHeroUrl = heroImagePrimaryOk ? heroImageUrl : heroImageFallbackOk ? freshHeroImageUrl : null;

  useTrackScreen("explore");

  useEffect(() => {
    setHeroImageFailed(false);
    setHeroFallbackFailed(false);
  }, [heroImageUrl]);

  useEffect(() => {
    if (status === "idle") {
      locate();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [status]);

  useEffect(() => {
    if (status === "ready" && !userPos) {
      getCurrentPosition()
        .then((pos) => setUserPos({ lat: pos.coords.latitude, lng: pos.coords.longitude }))
        .catch(() => {});
    }
  }, [status, userPos]);

  const visibleSites =
    activeCategory === "All" ? sites : sites.filter((s) => s.category === activeCategory);

  const sitesWithDistance = useMemo(
    () =>
      visibleSites
        .map((site) => ({
          site,
          distanceMeters: userPos ? haversineMeters(userPos.lat, userPos.lng, site.lat, site.lng) : null,
        }))
        .sort((a, b) => (a.distanceMeters ?? 0) - (b.distanceMeters ?? 0)),
    [visibleSites, userPos],
  );

  return (
    <div className="px-4 sm:px-6 md:px-8 lg:px-[32px] py-6 md:py-[32px] max-w-[1260px]">
      <p className="font-heading font-semibold text-[20px] sm:text-[24px] text-text-primary">
        {city?.name || t("explore.locating")}
      </p>
      <p className="font-medium text-[11px] text-text-secondary tracking-[1px] mt-[4px]">{t("explore.culturalDiscovery")}</p>

      <div className="relative bg-secondary-purple rounded-[24px] w-full h-[320px] overflow-hidden mt-[16px]">
        {displayedHeroUrl ? (
          <img
            src={displayedHeroUrl}
            alt={city?.name || ""}
            onError={() => {
              if (heroImagePrimaryOk) {
                setHeroImageFailed(true);
                track("Hero Image Broken", { city_id: city?.id, recovered: false });
              } else {
                setHeroFallbackFailed(true);
                track("Hero Image Broken", { city_id: city?.id, recovered: false, fallback: true });
              }
            }}
            className="absolute inset-0 size-full object-cover"
          />
        ) : (
          <div className="absolute inset-0 bg-gradient-to-r from-[#2d2a5c] to-secondary-purple" />
        )}
      </div>

      <div className="bg-surface-lavender rounded-[16px] mt-[24px] px-[24px] py-[14px]">
        <p className="font-medium text-[11px] text-secondary-purple tracking-[0.44px]">
          {status === "locating" && t("explore.statusLocatingYou")}
          {status === "loading-sites" && t("explore.statusDiscoveringSites")}
          {status === "ready" && t("explore.statusNearby")}
          {status === "error" && t("explore.statusLocationUnavailable")}
          {status === "idle" && t("explore.statusLocatingYou")}
        </p>
        <p className="text-[14px] text-text-secondary mt-[4px]">
          {status === "locating" && t("explore.findingPlace")}
          {status === "loading-sites" && t("explore.gatheringSites")}
          {status === "ready" && t("explore.sitesWithinRange", { count: sites.length })}
          {status === "error" && (error || t("explore.locationUnavailable"))}
          {status === "idle" && t("explore.findingPlace")}
        </p>
        {status === "error" && (
          <button
            onClick={locate}
            className="mt-[10px] bg-secondary-purple text-white text-[12px] font-medium rounded-[16px] px-[14px] py-[6px]"
          >
            {t("explore.tryAgain")}
          </button>
        )}
      </div>

      <p className="font-medium text-[12px] text-text-primary tracking-[0.48px] mt-[20px]">
        {t("explore.nearbyWithinRange")}{city?.locality ? ` · ${city.locality.toUpperCase()}` : ""}
      </p>

      <div className="flex gap-[10px] mt-[16px] flex-wrap">
        {CATEGORIES.map((cat) => (
          <TagPill
            key={cat}
            label={cat === "All" ? t("explore.allCategories") : t(CATEGORY_LABEL_KEYS[cat])}
            active={activeCategory === cat}
            accent={CATEGORY_ACCENTS[cat]}
            onClick={() => {
              track("Site Filter Toggled", { tag: cat, active: activeCategory !== cat, view: "nearby" });
              setActiveCategory(cat);
            }}
          />
        ))}
      </div>

      <div className="flex flex-wrap gap-[20px] mt-[20px]">
        {sitesWithDistance.map(({ site, distanceMeters }) => (
          <PoiCardWithImage
            key={site.id}
            site={site}
            distance={formatDistance(distanceMeters)}
            onClick={() => setSelectedSiteName(site.name)}
          />
        ))}
        {status === "ready" && sitesWithDistance.length === 0 && (
          <p className="text-text-secondary text-[14px]">{t("explore.noSitesForCategory")}</p>
        )}
      </div>

      {selectedSiteName && city && (
        <SiteDetailModal
          siteName={selectedSiteName}
          cityId={city.id}
          cityName={city.name}
          source="explore"
          onClose={() => setSelectedSiteName(null)}
        />
      )}
    </div>
  );
}
